version: "2.3"
services:
  nginx:
    build: nginx/
    ports:
      - "8043:8043"
    volumes:
      - /root/docker_lab/1_base/volumes/docker-compose/nginx/www/:/var/www
    depends_on:
      php:
        condition: service_healthy
    environment:
     - ENV=development

  php:
    build: php/
    volumes:
      - /root/docker_lab/1_base/volumes/docker-compose/php/www/:/var/www
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s  
